logstash:
  restart: always
  tty: true
  environment:
    VIRTUAL_HOST: logstash
    VIRTUAL_PORT: ${virtual_ports}
  ports:
  - "514:514/tcp"   # Palo Alto
  - "514:514/udp"   # Squid
  - "5000:5000/udp" # Logspout
  - "5044:5044/tcp" # AD
  - "5045:5045/tcp" # Kaspersky
  - "5138:5138/tcp" # bash-history
  - "5139:5139/tcp" # ssh
  - "5140:5140/tcp" # Yum
  - "8050:8050/tcp" # Talend
  - "8051:8051/udp" # Switch
  - "8052:8052/tcp" # Talend
  - "9980:9980/udp" # Netflow
  volumes:
  - /srv/logstash/conf.d:/etc/logstash/conf.d/:ro
  - /srv/logstash/geoip:/etc/logstash/geoip/:ro
  - /srv/logstash/templates:/etc/logstash/templates/:ro
  - /srv/logstash/patterns:/etc/logstash/patterns/:ro
  command:
  - logstash
  - -f
  - /etc/logstash/conf.d
  - --auto-reload
  image: logstash:2.3.3
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
