.catalog:
  name: "Logstash"
  version: "2.3.3-custom"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: commandline
      label: "Extra commandline arguments"
      description: "Please refer to logstash documentation if needed."
      type: "string"
      required: true
      default: "-w 1"
    - variable: "virtual_ports"
      description: |
        Notify nginx-rancher-rp with ports to forward, set to "auto" for automatic discovery.
      label: "List of integers separated by space"
      default: "auto"
      required: true
      type: "string"
    - variable: affinity
      label: "Rancher scheduler affinity, based on hosts labels MUST NOT EQUALS!"
      description: "Can be any key=value pair..."
      type: "string"
      required: true
      default: "com.agefos.=value"
logstash-indexer:
  metadata:
    logstash:
      outputs: |
        ${indexer_outputs}
