.catalog:
  name: "Logstash"
  version: "2.3.3-custom"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
        stdout {
            codec => rubydebug
        }
    - variable: "virtual_ports"
      description: |
        Ports to forward to nginx-rancher-rp, set to "auto" for automatic discovery.
      label: "List of integers separated by space"
      default: "auto"
      required: true
      type: "string"
logstash-indexer:
  metadata:
    logstash:
      outputs: |
        ${indexer_outputs}
