.catalog:
  name: "Logstash"
  version: "2.3.3-custom"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
        stdout {
            codec => rubydebug
        }
    # - variable: "elasticsearch_link"
    #   description: |
    #     stack/service link or external service link to elasticsearch
    #     cluster.
    #   label: "Elasticsearch stack/service"
    #   default: "es/elasticsearch-clients"
    #   required: true
    #   type: "service"
logstash-indexer:
  metadata:
    logstash:
      outputs: |
        ${indexer_outputs}
