.catalog:
  name: "Kibana"
  version: "4.5-rancher1-custom"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    # - variable: "elasticsearch_link"
    #   description: "Link to elasticsearch service or stack/service"
    #   label: "Elasticsearch source"
    #   type: "service"
    #   required: true
    #   default: "elasticsearch/elasticsearch-clients"
    - variable: "kibana_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true
    - variable: "kibana_fqdn"
      description: "Nginx Reverse Proxy FQDN for Kibana Web Interface"
      label: "Kibana FQDN"
      type: "string"
      required: true
      default: "kibana.services.agefos-pme.intra"
