masters:
  image: agefospme/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-master,datavolume-masters
  volumes_from:
    - datavolume-masters
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1

datavolume-masters:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - ${base_dir}/es/master/data:/usr/share/elasticsearch/data
    - ${base_dir}/es/master/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4
base-master:
  labels:
    elasticsearch.master.config.version: '0'
    io.rancher.container.hostname_override: container_name
  image: elasticsearch:2.4
  net: "container:masters"
  volumes_from:
    - datavolume-masters
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1

datanodes:
  image: agefospme/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-datanode,datavolume-datanode
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  volumes_from:
    - datavolume-datanode
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1

datavolume-datanode:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - ${base_dir}/es/datanode/data:/usr/share/elasticsearch/data
    - ${base_dir}/es/datanode/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4
base-datanode:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
  image: elasticsearch:2.4
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh
  volumes_from:
    - datavolume-datanode
  net: "container:datanodes"
  ulimits:
    memlock:
      soft: -1
      hard: -1

clients:
  image: agefospme/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-clients,datavolume-clients
  volumes_from:
    - datavolume-clients
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1

datavolume-clients:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - ${base_dir}/es/client/data:/usr/share/elasticsearch/data
    - ${base_dir}/es/client/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1

base-clients:
  labels:
    elasticsearch.client.config.version: '0'
    io.rancher.container.hostname_override: container_name
  image: elasticsearch:2.4
  volumes_from:
    - datavolume-clients
  net: "container:clients"
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1

kopf:
  image: rancher/kopf:v0.4.0
  ports:
    - "${kopf_port}:80"
  environment:
    VIRTUAL_HOST: "${kopf_fqdn}"
    VIRTUAL_PORT: "${kopf_port}"
    KOPF_SERVER_NAME: 'es.dev'
    KOPF_ES_SERVERS: 'clients.elasticsearch:9200'
  labels:
    io.rancher.container.hostname_override: container_name
