nginx-proxy:
  image: jwilder/nginx-proxy:latest
  labels:
    io.rancher.container.network: true
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: 'true'
  ports:
   - "80:80"
   - "443:443"
  volumes:
    - '${base_dir}/certs:/etc/nginx/certs:ro'
    - '${base_dir}/nginx/vhost.d:/etc/nginx/vhost.d'
    - '${base_dir}/nginx/html:/usr/share/nginx/html'
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
