.catalog:
  name: "NGinx-ReverseProxy"
  version: "latest-custom"
  description: "Reverse proxy for the masses"
  questions:
    - variable: base_dir
      description: "Base directory for configuration files."
      label: "Base directory"
      type: "string"
      required: true
      default: "/srv"

# nginx-proxy:
#   metadata:
#     nginx:
#       conf:
#         servername: "kibana"
#         upstream_port: 5601
